namespace SparkCore.Analytics.Syntax;

public enum SyntaxKind
{
    // TOKENS
    BadToken,
    EndOfFileToken,
    WhiteSpaceToken,
    NumberToken,
    StringToken,
    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    OpenParentesisToken,
    CloseParentesisToken,
    CommaToken,
    ColonToken,
    OpenBraceToken,
    CloseBraceToken,
    IdentifierToken,
    BangToken,
    EqualsToken,
    TildeToken,
    HatToken,
    AmpersandToken,
    AmpersandAmpersandToken,
    PibeToken,
    PibePibeToken,
    BangEqualsToken,
    EqualsEqualsToken,
    LessToken,
    LessOrEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    
    //KEYWORDS
    BreakKeyword,
    ContinueKeyword,
    DoKeyword,
    ElseKeyword,
    FalseKeyword,
    ForKeyword,
    FunctionKeyword,
    IfKeyword,
    ToKeyword,
    TrueKeyword,
    LetKeyword,
    VarKeyword,
    WhileKeyword,

    //NODES
    CompilationUnit,
    FunctionDeclaration,
    GlobalStatement,
    Parameter,
    TypeClause,
    ElseClause,

    //STATEMENTS
    BlockStatement,
    ExpressionStatement,
    VariableDeclarationStatement,
    IfStatement,
    WhileStatement,
    DoWhileStatement,
    ForStatement,
    BreakStatement,
    ContinueStatement,

    // EXPRESSIONS
    LiteralExpression,
    NameExpression,
    UnaryExpression,
    BinaryExpression,
    ParenthesizedExpression,
    AssignmentExpression,
    CallExpression,
}
